import type { ExpoConfig, ConfigContext } from "@expo/config";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "MemoStacker",
  slug: "memologminute",
  version: "1.5",
  orientation: "default",
  icon: "./src/assets/icons/ios-light.png",
  scheme: "memolog",
  userInterfaceStyle: "automatic",
  ios: {
    supportsTablet: true,
    bundleIdentifier: "com.ezgna.testthree",
    infoPlist: {
      CFBundleAllowMixedLocalizations: true,
      CFBundleLocalizations: ["en", "ja"],
      CFBundleDevelopmentRegion: "en",
      ITSAppUsesNonExemptEncryption: false,
      NSUserTrackingUsageDescription: "We use this permission to provide personalized ads.",
    },
    icon: {
      dark: "./src/assets/icons/ios-dark.png",
      light: "./src/assets/icons/ios-light.png",
      tinted: "./src/assets/icons/ios-tinted.png",
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: "./src/assets/icons/adaptive-icon.png",
      monochromeImage: "./src/assets/icons/adaptive-icon.png",
      backgroundColor: "#ffffff",
    },
    package: "com.ezgna.memolog",
    edgeToEdgeEnabled: true,
  },
  locales: {
    ja: "./languages/ja.json",
  },
  experiments: {
    typedRoutes: true,
  },
  owner: "ezgna",
  extra: {
    eas: {
      projectId: "883709c0-cd67-4849-aad0-20c519e9a69d",
    },
  },
  plugins: [
    "expo-localization",
    "expo-font",
    "expo-asset",
    "expo-secure-store",
    "expo-sqlite",
    "expo-tracking-transparency",
    [
      "expo-splash-screen",
      {
        image: "./src/assets/icons/splash-icon-dark.png",
        imageWidth: 200,
        resizeMode: "contain",
        backgroundColor: "#ffffff",
        dark: {
          image: "./src/assets/icons/splash-icon-light.png",
          backgroundColor: "#000000",
        },
      },
    ],
    "expo-router",
    [
      "@react-native-google-signin/google-signin",
      {
        iosUrlScheme: "com.googleusercontent.apps.110368176913-u7anooc46iggk9n2ksi81pii7e5uqaas",
      },
    ],
    [
      "expo-build-properties",
      {
        ios: {
          useFrameworks: "static",
          extraPods: [{ name: "GoogleMobileAdsMediationUnity" }],
        },
      },
    ],
    [
      "react-native-google-mobile-ads",
      {
        iosAppId: "ca-app-pub-4363360791941587~3360620576",
        androidAppId: "ca-app-pub-4363360791941587~3324694963",
        skAdNetworkItems: [
          "cstr6suwn9.skadnetwork",
          "4fzdc2evr5.skadnetwork",
          "2fnua5tdw4.skadnetwork",
          "ydx93a7ass.skadnetwork",
          "p78axxw29g.skadnetwork",
          "v72qych5uu.skadnetwork",
          "ludvb6z3bs.skadnetwork",
          "cp8zw746q7.skadnetwork",
          "3sh42y64q3.skadnetwork",
          "c6k4g5qg8m.skadnetwork",
          "s39g8k73mm.skadnetwork",
          "3qy4746246.skadnetwork",
          "f38h382jlk.skadnetwork",
          "hs6bdukanm.skadnetwork",
          "mlmmfzh3r3.skadnetwork",
          "v4nxqhlyqp.skadnetwork",
          "wzmmz9fp6w.skadnetwork",
          "su67r6k2v3.skadnetwork",
          "yclnxrl5pm.skadnetwork",
          "t38b2kh725.skadnetwork",
          "7ug5zh24hu.skadnetwork",
          "gta9lk7p23.skadnetwork",
          "vutu7akeur.skadnetwork",
          "y5ghdn5j9k.skadnetwork",
          "v9wttpbfk9.skadnetwork",
          "n38lu8286q.skadnetwork",
          "47vhws6wlr.skadnetwork",
          "kbd757ywx3.skadnetwork",
          "9t245vhmpl.skadnetwork",
          "a2p9lx4jpn.skadnetwork",
          "22mmun2rn5.skadnetwork",
          "44jx6755aq.skadnetwork",
          "k674qkevps.skadnetwork",
          "4468km3ulz.skadnetwork",
          "2u9pt9hc89.skadnetwork",
          "8s468mfl3y.skadnetwork",
          "klf5c3l5u5.skadnetwork",
          "ppxm28t8ap.skadnetwork",
          "kbmxgpxpgc.skadnetwork",
          "uw77j35x4d.skadnetwork",
          "578prtvx9j.skadnetwork",
          "4dzt52r2t5.skadnetwork",
          "tl55sbb4fm.skadnetwork",
          "c3frkrj4fj.skadnetwork",
          "e5fvkxwrpn.skadnetwork",
          "8c4e2ghe7u.skadnetwork",
          "3rd42ekr43.skadnetwork",
          "97r2b46745.skadnetwork",
          "3qcr597p9d.skadnetwork",
          "294l99pt4k.skadnetwork",
          "m8dbw4sv7c.skadnetwork",
          "424m5254lk.skadnetwork",
          "238da6jt44.skadnetwork",
          "k6y4y55b64.skadnetwork",
          "5a6flpkh64.skadnetwork",
          "f7s53z58qe.skadnetwork",
          "zq492l623r.skadnetwork",
          "mp6xlyr22a.skadnetwork",
          "5l3tpt7t6e.skadnetwork",
          "w9q455wk68.skadnetwork",
          "4pfyvq9l8r.skadnetwork",
          "9nlqeag3gk.skadnetwork",
          "9rd848q2bz.skadnetwork",
          "f73kdq92p3.skadnetwork",
          "prcb7njmu6.skadnetwork",
          "n9x2a789qt.skadnetwork",
          "zmvfpc5aq8.skadnetwork",
          "av6w8kgt66.skadnetwork",
          "pwa73g5rt2.skadnetwork",
          "xga6mpmplv.skadnetwork",
          "wg4vff78zm.skadnetwork",
          "lr83yxwka7.skadnetwork",
          "5tjdwbrq8w.skadnetwork",
          "glqzh8vgby.skadnetwork",
          "feyaarzu9v.skadnetwork",
          "6yxyv74ff7.skadnetwork",
          "mqn7fxpca7.skadnetwork",
          "vhf287vqwu.skadnetwork",
          "g6gcrrvk4p.skadnetwork",
          "v79kvwwj4g.skadnetwork",
          "32z4fx6l9h.skadnetwork",
          "a8cz6cu7e5.skadnetwork",
          "5f5u5tfb26.skadnetwork",
          "5lm9lj6jb7.skadnetwork",
          "4w7y6s5ca2.skadnetwork",
          "mj797d8u6f.skadnetwork",
          "488r3q3dtq.skadnetwork",
          "x44k69ngh6.skadnetwork",
        ],
      },
    ],
    [
      "./plugins/with-android-unity-mediation",
      {
        playServicesAds: "24.5.0",
        unitySdk: "4.16.0",
        unityAdapter: "4.16.0.0",
        overwriteXml: false,
      },
    ],
  ],
});
